- name: Install and Configure Nginx
  hosts: nginx
  become: true

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and Enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create default index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Nginx Web Server is Running</h1>"
